#!/usr/bin/env python3
"""Emit coop-config.json from the linker map.

The browser wrapper needs to know where the co-op mailbox lives in EWRAM.
That address moves whenever the ROM is rebuilt with changed code, so it must
never be hardcoded on the JS side. Run this after `make modern`:

    python3 tools/coop/emit_config.py pokeemerald_modern.map coop-config.json

The wrapper still verifies the magic word at the address before trusting it,
so a stale config fails loudly instead of corrupting random EWRAM.
"""

import json
import re
import sys

# Keep in sync with include/net_link.h
EXPECTED = {
    "NET_MAILBOX_MAGIC": 0x504F4F43,
    "NET_PROTOCOL_VERSION": 1,
    "NET_MAX_PLAYERS": 2,
    "NET_RING_SLOTS": 8,
    "CMD_LENGTH": 8,
    "MAILBOX_SIZE": 0x1A0,
}

WANTED = ("gNetMailbox", "gNetLinkActive")


def parse_map(path):
    """Pull symbol addresses out of a GNU ld map file."""
    found = {}
    # Map lines look like:  "                0x0201a3d8                gNetMailbox"
    rx = re.compile(r"^\s+0x([0-9a-fA-F]+)\s+(\S+)\s*$")
    with open(path, errors="replace") as fh:
        for line in fh:
            m = rx.match(line.rstrip("\n"))
            if not m:
                continue
            addr, sym = m.groups()
            if sym in WANTED and sym not in found:
                found[sym] = int(addr, 16)
    return found


def main(argv):
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2

    map_path, out_path = argv[1], argv[2]
    syms = parse_map(map_path)

    missing = [s for s in WANTED if s not in syms]
    if missing:
        print(
            f"error: {', '.join(missing)} not found in {map_path}.\n"
            "Is this a co-op build? Check that src/net_link.c compiled in.",
            file=sys.stderr,
        )
        return 1

    mailbox = syms["gNetMailbox"]
    active = syms["gNetLinkActive"]

    # gNetLinkActive is declared immediately after the mailbox, so the gap is a
    # free structural check that the C struct and this file still agree.
    gap = active - mailbox
    if gap != EXPECTED["MAILBOX_SIZE"]:
        print(
            f"warning: mailbox-to-gNetLinkActive gap is 0x{gap:X}, expected "
            f"0x{EXPECTED['MAILBOX_SIZE']:X}. struct NetMailbox may have changed "
            "without this script being updated.",
            file=sys.stderr,
        )

    if not (0x02000000 <= mailbox < 0x02040000):
        print(
            f"error: gNetMailbox at 0x{mailbox:08X} is outside EWRAM.",
            file=sys.stderr,
        )
        return 1

    config = {
        "_comment": "Generated by tools/coop/emit_config.py. Do not edit.",
        "mailboxAddress": mailbox,
        "mailboxAddressHex": f"0x{mailbox:08X}",
        "netLinkActiveAddress": active,
        "mailboxSize": gap,
        "magic": EXPECTED["NET_MAILBOX_MAGIC"],
        "protocolVersion": EXPECTED["NET_PROTOCOL_VERSION"],
        "maxPlayers": EXPECTED["NET_MAX_PLAYERS"],
        "ringSlots": EXPECTED["NET_RING_SLOTS"],
        "cmdLength": EXPECTED["CMD_LENGTH"],
        # Byte offsets within the mailbox, mirroring struct NetMailbox.
        "offsets": {
            "magic": 0x00,
            "version": 0x04,
            "hostStatus": 0x05,
            "localId": 0x06,
            "playerCount": 0x07,
            "outHead": 0x08,
            "outTail": 0x09,
            "inHead": 0x0A,
            "inTail": 0x0C,
            "out": 0x10,
            "in": 0x90,
        },
    }

    with open(out_path, "w") as fh:
        json.dump(config, fh, indent=2)
        fh.write("\n")

    print(f"wrote {out_path}: mailbox at 0x{mailbox:08X}, size 0x{gap:X}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
